export type Property = {
  id: string
  title: string
  titleEs: string
  address: string
  city: string
  state: string
  zip: string
  price: number
  bedrooms: number
  bathrooms: number
  sqft: number
  type: 'House' | 'Condo' | 'Townhouse' | 'Multi-Family'
  status: 'For Sale' | 'Under Contract' | 'Sold'
  yearBuilt: number
  description: string
  descriptionEs: string
  features: string[]
  images: string[]
  agent: {
    name: string
    phone: string
    email: string
    photo: string
  }
  listedDate: string
  neighborhood: string
}

export const properties: Property[] = [
  {
    id: '1',
    title: 'Beautiful Family Home in Quiet Neighborhood',
    titleEs: 'Hermosa Casa Familiar en Vecindario Tranquilo',
    address: '2847 Calle del Sol',
    city: 'San Antonio',
    state: 'TX',
    zip: '78201',
    price: 285000,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1950,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2005,
    description: 'Spacious 4-bedroom home in a quiet neighborhood. Updated kitchen, hardwood floors throughout, and a large backyard perfect for family gatherings.',
    descriptionEs: 'Espaciosa casa de 4 habitaciones en un vecindario tranquilo. Cocina actualizada, pisos de madera en toda la casa y un gran patio trasero perfecto para reuniones familiares.',
    features: ['2-Car Garage', 'Updated Kitchen', 'Large Backyard', 'Hardwood Floors', 'Central A/C', 'Laundry Room'],
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-06-15',
    neighborhood: 'Westside',
  },
  {
    id: '2',
    title: 'Modern Condo Near Downtown',
    titleEs: 'Moderno Condominio Cerca del Centro',
    address: '540 Avenida Central, Apt 3B',
    city: 'Houston',
    state: 'TX',
    zip: '77002',
    price: 195000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    type: 'Condo',
    status: 'For Sale',
    yearBuilt: 2018,
    description: 'Sleek modern condo just minutes from downtown. Open floor plan, stainless steel appliances, and a private balcony with city views.',
    descriptionEs: 'Elegante condominio moderno a minutos del centro. Planta abierta, electrodomésticos de acero inoxidable y un balcón privado con vistas a la ciudad.',
    features: ['Private Balcony', 'City View', 'Modern Appliances', 'Building Gym', '24-hr Security', 'Parking Included'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-06-20',
    neighborhood: 'Downtown',
  },
  {
    id: '3',
    title: 'Charming Townhouse with Patio',
    titleEs: 'Encantador Townhouse con Patio',
    address: '1203 Rosa Linda Dr',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    price: 340000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2100,
    type: 'Townhouse',
    status: 'Under Contract',
    yearBuilt: 2015,
    description: 'Stunning 3-bedroom townhouse with a private patio and attached garage. Located in a gated community with a pool and playground.',
    descriptionEs: 'Impresionante townhouse de 3 habitaciones con patio privado y garaje adjunto. Ubicado en comunidad cerrada con alberca y área de juegos.',
    features: ['Gated Community', 'Pool', 'Private Patio', 'Attached Garage', 'Playground', 'Guest Room'],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-05-28',
    neighborhood: 'Oak Lawn',
  },
  {
    id: '4',
    title: 'Spacious Home with Large Lot',
    titleEs: 'Espaciosa Casa con Terreno Grande',
    address: '4512 Paloma Ave',
    city: 'El Paso',
    state: 'TX',
    zip: '79901',
    price: 225000,
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2800,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 1998,
    description: 'Rare 5-bedroom home on a large corner lot. Freshly painted, new roof, and updated bathrooms. Perfect for a large family or multigenerational living.',
    descriptionEs: 'Rara casa de 5 habitaciones en lote de esquina grande. Recién pintada, techo nuevo y baños remodelados. Perfecta para familia grande o vivienda multigeneracional.',
    features: ['Corner Lot', 'New Roof 2024', 'Renovated Bathrooms', 'Additional Room', 'Large Yard', 'Multigenerational Layout'],
    images: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
      'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=800&q=80',
    ],
    agent: { name: 'Roberto Vega', phone: '(915) 555-0404', email: 'roberto@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
    listedDate: '2026-07-01',
    neighborhood: 'Eastside',
  },
  {
    id: '5',
    title: 'Investment Duplex - Great Income Potential',
    titleEs: 'Dúplex de Inversión - Gran Potencial de Ingreso',
    address: '788 Calle Esperanza',
    city: 'San Antonio',
    state: 'TX',
    zip: '78210',
    price: 390000,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 2400,
    type: 'Multi-Family',
    status: 'For Sale',
    yearBuilt: 2010,
    description: 'Excellent investment opportunity. Both units are currently rented generating $2,800/month. Each unit has 2 beds, 1 bath, separate utilities, and private parking.',
    descriptionEs: 'Excelente oportunidad de inversión. Ambas unidades están rentadas generando $2,800/mes. Cada unidad tiene 2 recámaras, 1 baño, servicios separados y estacionamiento privado.',
    features: ['2 Rented Units', '$2,800/mo Income', 'Separate Utilities', 'Private Parking', 'Stable Tenants', 'High Rental Demand'],
    images: [
      'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-06-10',
    neighborhood: 'Southside',
  },
  {
    id: '6',
    title: 'Cozy Starter Home Near Schools',
    titleEs: 'Acogedora Casa Inicial Cerca de Escuelas',
    address: '321 Flores Street',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    price: 310000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1450,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2001,
    description: 'Perfect starter home in a family-friendly neighborhood. Walking distance to top-rated schools, parks, and shopping. Move-in ready.',
    descriptionEs: 'Casa inicial perfecta en vecindario familiar. A pocas cuadras de escuelas de primer nivel, parques y tiendas. Lista para mudarse.',
    features: ['Move-In Ready', 'Near Schools', 'Family-Friendly', 'Nearby Park', 'Open Kitchen', 'Backyard'],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-07-03',
    neighborhood: 'East Austin',
  },
  {
    id: '7',
    title: 'Luxury Home with Pool and Guest Suite',
    titleEs: 'Casa de Lujo con Alberca y Suite de Visitas',
    address: '9015 Sendero Ridge',
    city: 'San Antonio',
    state: 'TX',
    zip: '78256',
    price: 675000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2019,
    description: 'Stunning luxury home in the prestigious Sendero Ranch community. Chef\'s kitchen, resort-style pool, outdoor kitchen, and a private guest suite.',
    descriptionEs: 'Impresionante casa de lujo en la prestigiosa comunidad Sendero Ranch. Cocina de chef, alberca estilo resort, cocina exterior y suite privada de visitas.',
    features: ['Resort-Style Pool', "Chef's Kitchen", 'Outdoor Kitchen', 'Guest Suite', 'Wine Cellar', 'Gated Community'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-06-01',
    neighborhood: 'Sendero Ranch',
  },
  {
    id: '8',
    title: 'Compact Studio Condo in Arts District',
    titleEs: 'Estudio Compacto en el Distrito de las Artes',
    address: '210 Commerce St, Unit 14A',
    city: 'Dallas',
    state: 'TX',
    zip: '75202',
    price: 145000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 620,
    type: 'Condo',
    status: 'For Sale',
    yearBuilt: 2016,
    description: 'Smart and stylish studio condo in the heart of Dallas Arts District. Floor-to-ceiling windows, exposed concrete, and walkable to everything.',
    descriptionEs: 'Estudio inteligente y moderno en el corazón del Distrito de las Artes de Dallas. Ventanas de piso a techo, concreto expuesto y todo a pie.',
    features: ['Floor-to-Ceiling Windows', 'Exposed Concrete', 'Walkable Location', 'Shared Rooftop Deck', 'Bike Included', 'Pet-Friendly'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-07-02',
    neighborhood: 'Arts District',
  },
  {
    id: '9',
    title: 'Renovated Bungalow with Modern Finishes',
    titleEs: 'Bungalow Renovado con Acabados Modernos',
    address: '1847 Blanco Rd',
    city: 'San Antonio',
    state: 'TX',
    zip: '78212',
    price: 268000,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 980,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 1952,
    description: 'Completely renovated 1950s bungalow in the King William adjacent area. New electrical, plumbing, roof, and a gorgeous modern kitchen.',
    descriptionEs: 'Bungalow completamente renovado de los años 50 cerca del área King William. Eléctrico, plomería, techo nuevos y una hermosa cocina moderna.',
    features: ['Fully Renovated', 'New Kitchen', 'New Roof', 'New Plumbing', 'Original Hardwood Floors', 'Charming Patio'],
    images: [
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-06-25',
    neighborhood: 'King William Adjacent',
  },
  {
    id: '10',
    title: 'Large Family Home Near Greenbelt',
    titleEs: 'Gran Casa Familiar Cerca del Cinturón Verde',
    address: '3308 Barton Hills Dr',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    price: 520000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3100,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2008,
    description: 'Spacious 4-bed home backing up to the Barton Creek Greenbelt. Huge deck, mature trees, and a rare 3-car garage in the heart of South Austin.',
    descriptionEs: 'Espaciosa casa de 4 habitaciones junto al Cinturón Verde de Barton Creek. Gran terraza, árboles maduros y un raro garaje para 3 autos en el sur de Austin.',
    features: ['Greenbelt Adjacent', '3-Car Garage', 'Large Deck', 'Mature Trees', 'Gourmet Kitchen', 'Storage Room'],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-06-18',
    neighborhood: 'Barton Hills',
  },
  {
    id: '11',
    title: 'New Construction Home in Master-Planned Community',
    titleEs: 'Casa Nueva en Comunidad Planificada',
    address: '712 Cielo Vista Blvd',
    city: 'El Paso',
    state: 'TX',
    zip: '79912',
    price: 299000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2250,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2026,
    description: 'Brand new construction in the highly sought-after Cielo Vista community. Energy-efficient, smart home features, and builder warranty included.',
    descriptionEs: 'Construcción completamente nueva en la muy solicitada comunidad Cielo Vista. Eficiencia energética, funciones de hogar inteligente y garantía del constructor incluida.',
    features: ['New Construction', 'Smart Home', "Builder's Warranty", 'Energy-Efficient', 'Community Pool', 'Playground'],
    images: [
      'https://images.unsplash.com/photo-1592595896551-12b371d546d5?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    ],
    agent: { name: 'Roberto Vega', phone: '(915) 555-0404', email: 'roberto@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
    listedDate: '2026-07-05',
    neighborhood: 'Cielo Vista',
  },
  {
    id: '12',
    title: 'Waterfront Townhouse on Buffalo Bayou',
    titleEs: 'Townhouse Frente al Agua en Buffalo Bayou',
    address: '4401 Allen Pkwy, Unit B',
    city: 'Houston',
    state: 'TX',
    zip: '77019',
    price: 415000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 2350,
    type: 'Townhouse',
    status: 'For Sale',
    yearBuilt: 2017,
    description: 'Rare waterfront townhouse steps from Buffalo Bayou Park. Rooftop terrace with downtown views, elevator, and a private 2-car garage.',
    descriptionEs: 'Raro townhouse frente al agua a pasos del Parque Buffalo Bayou. Terraza en la azotea con vistas al centro, elevador y garaje privado para 2 autos.',
    features: ['Waterfront', 'Rooftop Terrace', 'Downtown View', 'Private Elevator', '2-Car Garage', 'Luxury Finishes'],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-05-30',
    neighborhood: 'River Oaks Area',
  },
  {
    id: '13',
    title: 'Affordable 2-Bed Condo with Amenities',
    titleEs: 'Condominio de 2 Rec. Accesible con Amenidades',
    address: '6600 Hillcrest Ave, Unit 201',
    city: 'Dallas',
    state: 'TX',
    zip: '75205',
    price: 172000,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 890,
    type: 'Condo',
    status: 'For Sale',
    yearBuilt: 2004,
    description: 'Well-maintained 2-bedroom condo in a gated community near SMU. Community pool, fitness center, and covered parking. Great for first-time buyers.',
    descriptionEs: 'Condominio de 2 recámaras bien mantenido en comunidad cerrada cerca de SMU. Alberca comunitaria, gimnasio y estacionamiento techado. Ideal para compradores primerizos.',
    features: ['Gated Community', 'Pool', 'Fitness Center', 'Covered Parking', 'Near SMU', 'Great for First-Time Buyers'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-06-28',
    neighborhood: 'University Park',
  },
  {
    id: '14',
    title: 'Sprawling Ranch-Style Estate',
    titleEs: 'Espléndida Hacienda Estilo Rancho',
    address: '18200 Culebra Rd',
    city: 'San Antonio',
    state: 'TX',
    zip: '78023',
    price: 895000,
    bedrooms: 6,
    bathrooms: 5,
    sqft: 5200,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2003,
    description: 'Magnificent ranch-style estate on 2.5 acres. Six bedrooms, home theater, game room, resort pool, 4-car garage, and a detached casita.',
    descriptionEs: 'Magnífica hacienda estilo rancho en 2.5 acres. Seis recámaras, cine en casa, sala de juegos, alberca resort, garaje para 4 autos y casita separada.',
    features: ['2.5 Acres', 'Home Theater', 'Game Room', 'Resort Pool', '4-Car Garage', 'Detached Casita'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-05-15',
    neighborhood: 'Northwest Side',
  },
  {
    id: '15',
    title: 'Mid-Century Modern Near Medical Center',
    titleEs: 'Moderno Mid-Century Cerca del Centro Médico',
    address: '2903 Wroxton Rd',
    city: 'Houston',
    state: 'TX',
    zip: '77005',
    price: 445000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1780,
    type: 'House',
    status: 'Under Contract',
    yearBuilt: 1962,
    description: 'Iconic mid-century modern home fully renovated while preserving original character. Terrazzo floors, vaulted ceilings, and a lush landscaped backyard.',
    descriptionEs: 'Icónica casa moderna mid-century completamente renovada preservando su carácter original. Pisos de terrazo, techos abovedados y jardín exuberante.',
    features: ['Terrazzo Floors', 'Vaulted Ceilings', 'Fully Renovated', 'Lush Landscaping', 'Original Windows', 'Near Med Center'],
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-06-08',
    neighborhood: 'West University',
  },
  {
    id: '16',
    title: '4-Plex Investment Property',
    titleEs: 'Cuádruplex de Inversión',
    address: '3310 Cesar Chavez St',
    city: 'Austin',
    state: 'TX',
    zip: '78702',
    price: 780000,
    bedrooms: 8,
    bathrooms: 4,
    sqft: 3800,
    type: 'Multi-Family',
    status: 'For Sale',
    yearBuilt: 2012,
    description: '4-plex in the heart of East Austin. All units currently occupied at market rate, generating $6,400/month gross. Prime location near restaurants and nightlife.',
    descriptionEs: 'Cuádruplex en el corazón del Este de Austin. Todas las unidades ocupadas a precio de mercado, generando $6,400/mes brutos. Ubicación prime cerca de restaurantes.',
    features: ['4 Occupied Units', '$6,400/mo Income', 'East Austin Location', 'Separate Utilities', 'Parking Per Unit', 'High Demand'],
    images: [
      'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-05-20',
    neighborhood: 'East Austin',
  },
  {
    id: '17',
    title: 'Golf Course View Home in Upscale Gated Community',
    titleEs: 'Casa con Vista al Golf en Comunidad Cerrada Exclusiva',
    address: '504 Encino Rio',
    city: 'San Antonio',
    state: 'TX',
    zip: '78259',
    price: 550000,
    bedrooms: 4,
    bathrooms: 3.5,
    sqft: 3400,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2011,
    description: 'Elegant home overlooking the TPC San Antonio golf course. Open concept living, butler\'s pantry, media room, and a covered outdoor living area.',
    descriptionEs: 'Elegante casa con vista al campo de golf TPC San Antonio. Concepto abierto, despensa de mayordomo, sala de medios y área exterior cubierta.',
    features: ['Golf Course View', 'Open Concept', "Butler's Pantry", 'Media Room', 'Covered Outdoor Area', 'Private Community'],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-06-12',
    neighborhood: 'Stone Oak',
  },
  {
    id: '18',
    title: 'Historic Home in Walkable Neighborhood',
    titleEs: 'Casa Histórica en Vecindario Peatonal',
    address: '631 E Mistletoe Ave',
    city: 'San Antonio',
    state: 'TX',
    zip: '78212',
    price: 375000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1650,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 1928,
    description: 'Beautifully preserved 1920s craftsman home in the historic Monte Vista neighborhood. Original hardwoods, clawfoot tub, wraparound porch, and updated systems.',
    descriptionEs: 'Hermosa casa estilo craftsman de los años 20 en el histórico vecindario Monte Vista. Pisos originales, bañera clásica, porche envolvente y sistemas actualizados.',
    features: ['Built in 1928', 'Wraparound Porch', 'Original Hardwoods', 'Clawfoot Tub', 'Historic Neighborhood', 'Fully Walkable'],
    images: [
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-06-22',
    neighborhood: 'Monte Vista',
  },
  {
    id: '19',
    title: 'High-Rise Condo with Panoramic City Views',
    titleEs: 'Condominio en Torre con Vistas Panorámicas',
    address: '1600 Smith St, Floor 28',
    city: 'Houston',
    state: 'TX',
    zip: '77002',
    price: 320000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1250,
    type: 'Condo',
    status: 'For Sale',
    yearBuilt: 2014,
    description: 'Stunning 28th-floor condo in one of Houston\'s premier high-rises. Floor-to-ceiling windows, concierge, valet parking, and rooftop pool.',
    descriptionEs: 'Impresionante condominio en el piso 28 de uno de los mejores rascacielos de Houston. Ventanas de piso a techo, concierge, valet y alberca en azotea.',
    features: ['28th Floor', 'Panoramic Views', 'Concierge', 'Valet Parking', 'Rooftop Pool', 'Building Spa'],
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-07-04',
    neighborhood: 'Midtown',
  },
  {
    id: '20',
    title: 'Move-In Ready Townhouse Near Galleria',
    titleEs: 'Townhouse Listo para Mudarse Cerca de Galleria',
    address: '5520 Westheimer Rd, Unit C',
    city: 'Houston',
    state: 'TX',
    zip: '77056',
    price: 385000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1900,
    type: 'Townhouse',
    status: 'For Sale',
    yearBuilt: 2020,
    description: 'Like-new 3-story townhouse minutes from the Galleria. Open kitchen, quartz counters, hardwood floors, and a private rooftop deck perfect for entertaining.',
    descriptionEs: 'Townhouse de 3 pisos casi nuevo a minutos de la Galleria. Cocina abierta, encimeras de cuarzo, pisos de madera y terraza privada en azotea.',
    features: ['Like-New', 'Private Rooftop Deck', 'Quartz Counters', 'Hardwood Floors', 'Near Galleria', '3 Stories'],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    ],
    agent: { name: 'Carlos Reyes', phone: '(713) 555-0202', email: 'carlos@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/32.jpg' },
    listedDate: '2026-06-30',
    neighborhood: 'Galleria',
  },
  {
    id: '21',
    title: 'Fixer-Upper with Great Bones',
    titleEs: 'Casa para Remodelar con Gran Potencial',
    address: '887 S Zarzamora St',
    city: 'San Antonio',
    state: 'TX',
    zip: '78207',
    price: 138000,
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1200,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 1975,
    description: 'Great investment or first-home opportunity. Solid structure with original hardwoods hiding under carpet. Large lot, detached garage, and alley access.',
    descriptionEs: 'Gran oportunidad de inversión o primera casa. Estructura sólida con pisos de madera original bajo la alfombra. Lote grande, garaje separado y acceso por callejón.',
    features: ['Great Potential', 'Large Lot', 'Detached Garage', 'Hidden Hardwood Floors', 'Affordable Entry Price', 'Alley Access'],
    images: [
      'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?w=800&q=80',
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80',
    ],
    agent: { name: 'Roberto Vega', phone: '(915) 555-0404', email: 'roberto@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
    listedDate: '2026-07-06',
    neighborhood: 'Westside',
  },
  {
    id: '22',
    title: 'Executive Home in Plano Suburb',
    titleEs: 'Casa Ejecutiva en los Suburbios de Plano',
    address: '3204 Ridgewood Dr',
    city: 'Plano',
    state: 'TX',
    zip: '75025',
    price: 490000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 3650,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2007,
    description: 'Executive home in award-winning Plano ISD. Grand entry, formal dining, game room, 3-car garage, and a stunning backyard with pergola and fire pit.',
    descriptionEs: 'Casa ejecutiva en el galardonado distrito escolar de Plano. Entrada imponente, comedor formal, sala de juegos, garaje para 3 autos y patio con pérgola y fogata.',
    features: ['Plano ISD', 'Grand Entry', 'Game Room', '3-Car Garage', 'Pergola & Fire Pit', 'Formal Dining'],
    images: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-06-05',
    neighborhood: 'West Plano',
  },
  {
    id: '23',
    title: 'Modern Farmhouse in the Suburbs',
    titleEs: 'Casa de Granja Moderna en los Suburbios',
    address: '1102 Mockingbird Ln',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76107',
    price: 355000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2600,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2022,
    description: 'Beautiful modern farmhouse built in 2022. Shiplap accent walls, farmhouse sink, open floor plan, and a large covered back porch overlooking a greenbelt.',
    descriptionEs: 'Hermosa casa de granja moderna construida en 2022. Paredes de shiplap, fregadero rústico, planta abierta y amplio porche cubierto con vista al área verde.',
    features: ['Built in 2022', 'Shiplap Accent Walls', 'Farmhouse Sink', 'Open Floor Plan', 'Covered Porch', 'Greenbelt View'],
    images: [
      'https://images.unsplash.com/photo-1592595896551-12b371d546d5?w=800&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-06-17',
    neighborhood: 'Cultural District',
  },
  {
    id: '24',
    title: 'Downtown Loft with Exposed Brick',
    titleEs: 'Loft en el Centro con Ladrillo Expuesto',
    address: '415 N St Mary\'s St, Unit 5',
    city: 'San Antonio',
    state: 'TX',
    zip: '78205',
    price: 230000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 850,
    type: 'Condo',
    status: 'For Sale',
    yearBuilt: 2009,
    description: 'Chic downtown loft conversion with exposed brick walls, industrial steel beams, and polished concrete floors. Walking distance to the River Walk.',
    descriptionEs: 'Elegante conversión de loft en el centro con paredes de ladrillo expuesto, vigas de acero industrial y pisos de concreto pulido. A pie del River Walk.',
    features: ['Exposed Brick', 'Steel Beams', 'Polished Concrete', 'Walk to River Walk', 'High Ceilings', 'Industrial Windows'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    ],
    agent: { name: 'María González', phone: '(210) 555-0101', email: 'maria@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    listedDate: '2026-07-01',
    neighborhood: 'Downtown',
  },
  {
    id: '25',
    title: 'Energy-Efficient New Build in El Paso Hills',
    titleEs: 'Casa Nueva Eficiente en las Colinas de El Paso',
    address: '5503 Mesa Hills Dr',
    city: 'El Paso',
    state: 'TX',
    zip: '79912',
    price: 265000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1700,
    type: 'House',
    status: 'For Sale',
    yearBuilt: 2025,
    description: 'Nearly new 3-bedroom home with solar panels and energy-efficient construction. Mountain views, open kitchen, and a large covered patio perfect for El Paso evenings.',
    descriptionEs: 'Casa casi nueva de 3 habitaciones con paneles solares y construcción eficiente. Vistas a las montañas, cocina abierta y gran patio cubierto ideal para las noches de El Paso.',
    features: ['Solar Panels', 'Mountain Views', 'Nearly New', 'Covered Patio', 'Energy-Efficient', 'No HOA'],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1592595896551-12b371d546d5?w=800&q=80',
    ],
    agent: { name: 'Roberto Vega', phone: '(915) 555-0404', email: 'roberto@loslistos.com', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
    listedDate: '2026-06-29',
    neighborhood: 'Mesa Hills',
  },
  {
    id: '26',
    title: 'Corner Lot Townhouse with Rooftop',
    titleEs: 'Townhouse en Esquina con Azotea',
    address: '2201 Fairmount Ave',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76104',
    price: 298000,
    bedrooms: 2,
    bathrooms: 2.5,
    sqft: 1550,
    type: 'Townhouse',
    status: 'Under Contract',
    yearBuilt: 2021,
    description: 'Corner unit townhouse in the vibrant Fairmount Historic District. Private rooftop deck, 2-car garage, and walking distance to local restaurants and shops.',
    descriptionEs: 'Townhouse en esquina en el vibrante Distrito Histórico de Fairmount. Azotea privada, garaje para 2 autos y a pie de restaurantes y tiendas locales.',
    features: ['Corner Unit', 'Private Rooftop', '2-Car Garage', 'Historic District', 'Walkable', 'Built in 2021'],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    ],
    agent: { name: 'Ana Martínez', phone: '(214) 555-0303', email: 'ana@loslistos.com', photo: 'https://randomuser.me/api/portraits/women/65.jpg' },
    listedDate: '2026-06-14',
    neighborhood: 'Fairmount',
  },
]

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id)
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(price)
}
